WebBanGiay/WebBanGiay/Controllers/ShoeStoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanGiay.Models;

namespace WebBanGiay.Controllers
{
    public class ShoeStoreController : Controller
    {
        dbQLBanGiayDataContext data = new dbQLBanGiayDataContext();
        private List<GIAY> LayGiayMoi (int count)
        {
            return data.GIAYs.OrderByDescending(a => a.Ngaycapnhat).Take(count).ToList();
        }
        public ActionResult SPtheoloai(int id)
        {
            var giay = from s in data.GIAYs where s.MaLOAI==id select s;
            return View(giay);
        }
        public ActionResult Details(int id)
        {
            var giay= from g in data.GIAYs where g.MaGIAY==id select g;
            return View(giay.Single());
        }
        // GET: ShoeStore
        public ActionResult Index()
        {
            var sachMoi = LayGiayMoi(6);
            return View(sachMoi);
        }
    }
}

WebBanGiay/WebBanGiay/Views/ShoeStore/Details.cshtml
    @{
        ViewBag.Title = "Details";
        Layout = "~/Views/Shared/_LayoutUser.cshtml";
    }

    <h2 style="margin-bottom: 50px; text-align: center">THÔNG TIN CHI TIẾT GIÀY</h2>
    <div class="row">
        <div class="col-md-4 col-12" style="border: 1px solid red">
            <img src="~/image/g2.jpg" alt="Alternate Text" style="width: 90%" />
        </div>
        <div class="col-md-6 col-12">
            <h2 style="color:palevioletred"> @Model.TenGIAY </h2>

            $1000
            <div id="Datmua" class="col-md-4 col-8 btn btn-danger btn-block">
                <a href="@Url.Action("ThemGioHang", "GioHang", new {@iMagiay = @Model.MaGIAY,@strURL=Request.Url.ToString()})">
                    ĐẶT GIÀY
                </a>
            </div>
        </div>
        <br />

    </div>

WebBanGiay/WebBanGiay/Views/ShoeStore/Index.cshtml
@model IEnumerable<WebBanGiay.Models.GIAY>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

@foreach (var x in Model)
{
<a href="#">
    <div class="col-md-4 product-men">
        <div class="product-shoe-info shoe">
            <div class="men-pro-item">
                <div class="men-thumb-item">
                    <img src="~/image/g2.jpg" alt="">
                    <div class="men-cart-pro">
                        <div class="inner-men-cart-pro">
                            <a href="@Url.Action("Details", "ShoeStore", new {id=x.MaGIAY})" class="link-product-add-cart">Quick View</a>
                        </div>
                    </div>
                    <span class="product-new-top">New</span>
                </div>
                <div class="item-info-product">
                    <h4>
                        @x.TenGIAY
                    </h4>
                    <div class="info-product-price">
                        <div class="grid_meta">
                            <div class="product_price">
                                <div class="grid-price ">
                                    <span class="money ">@x.Giaban</span>
                                </div>
                            </div>
                            
                        </div>
                        
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>

    </div>
</a>
}